from enum import Enum

class Events(Enum):
    ACTIVEEVENT = 1
    KEYDOWN = 2
    KEYUP = 3
    MOUSEMOTION = 4
    MOUSEBUTTONUP = 5
    MOUSEBUTTONDOWN = 6
    JOYAXISMOTION = 7
    JOYBALLMOTION = 8
    JOYHATMOTION = 9
    JOYBUTTONUP = 10
    JOYBUTTONDOWN = 11
    VIDEORESIZE = 12
    VIDEOEXPOSE = 13
    USEREVENT = 14